/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2026, Roy Ratcliffe, Northumberland, United Kingdom
 */

#ifndef GPIO_H
#define GPIO_H

#include <gpiod.h>

/*!
 * \brief Generator for edge events read from a GPIO line request.
 *
 * \details This structure represents a generator that can be used to read edge
 * events from a GPIO line request. It maintains the state of the generator,
 * including the request to read from, the buffer to store the events, the
 * maximum number of events to generate, the number of events generated so far,
 * and the current index in the event buffer. The generator can be initialised
 * with a specific request, buffer, and maximum number of events, and then used
 * to fetch edge events one by one until the generator is exhausted or an error
 * occurs.
 *
 * \note The max_events field is used to limit the number of edge events
 * generated by the generator. Typically, this is the value returned by
 * gpiod_line_request_wait_edge_events, which indicates how many edge events are
 * currently available to read from the line request. By using this value as the
 * max_events parameter when initialising the generator, the generator can be
 * used to read all currently available edge events from the line request
 * without blocking or waiting for additional events to become available. This
 * allows for efficient processing of edge events as they occur, while also
 * providing a mechanism to limit the number of events read in a single
 * operation, which can help manage resource usage and ensure that the program
 * remains responsive.
 */
struct gpio_edge_event_generator {
  struct gpiod_line_request *request;     /*!< The GPIO line request to read edge events from. */
  struct gpiod_edge_event_buffer *buffer; /*!< The buffer used to store edge events read from the request. */
  size_t max_events;                      /*!< The maximum number of edge events to generate. */
  int num_events;                         /*!< The number of edge events generated. */
  unsigned long index;                    /*!< The current index in the edge event buffer. */
};

/*!
 * \brief Initialise an edge event generator.
 * \param generator The generator to initialise.
 * \param request The GPIO line request to read edge events from.
 * \param buffer The buffer used to store edge events.
 * \param max_events The maximum number of edge events to generate.
 */
void gpio_edge_event_generator_init(struct gpio_edge_event_generator *generator, /*!< The generator to initialise. */
                                    struct gpiod_line_request *request,          /*!< The GPIO line request to read edge events from. */
                                    struct gpiod_edge_event_buffer *buffer,      /*!< The buffer used to store edge events. */
                                    size_t max_events /*!< The maximum number of edge events to generate. */);

/*!
 * \brief Fetch the next edge event from a generator.
 * \param generator The generator to advance.
 * \param event The next edge event, or NULL when the generator is exhausted.
 * \return 1 when an event is produced, 0 when the generator is exhausted, or a negative error code on failure.
 */
int gpio_edge_event_generator_next(struct gpio_edge_event_generator *generator, struct gpiod_edge_event **event);

/*!
 * \brief Read edge events for a GPIO line request and yield them to a callback
 * function.
 *
 * \param request The GPIO line request to read edge events from.
 *
 * \param buffer The edge event buffer to store the read edge events.
 *
 * \param max_events The maximum number of edge events to read and yield to the
 * callback function.
 *
 * \param yield The callback function to which the read edge events will be
 * yielded. This function will be called for each edge event read from the
 * request, and the edge event will be passed as an argument to the callback
 * function. The callback function can perform any necessary processing on the
 * edge event, such as logging, analysing, or storing the event data. The
 * callback function can also use the user_data argument to access additional
 * context or state information needed for processing the edge events.
 *
 * Its return value will be accumulated and returned by
 * gpio_line_request_read_edge_events. This allows the callback function to
 * contribute to the overall result of the edge event processing, such as
 * counting the number of events processed, or returning an error code if a
 * certain condition is met.
 *
 * \param user_data A pointer to user-defined data that will be passed to the
 * callback function for each edge event. This can be used to provide additional
 * context or state information to the callback function when processing the
 * edge events.
 *
 * \return 0 on success, or a negative error code on failure. If the function
 * returns a negative error code, it indicates that an error occurred while
 * reading edge events from the request or while yielding the events to the
 * callback function. The specific error code can provide more information about
 * the nature of the error, such as whether it was a failure to read edge
 * events, an error in the callback function, or some other issue.
 */
int gpio_line_request_read_edge_events(struct gpiod_line_request *request, struct gpiod_edge_event_buffer *buffer, size_t max_events,
                                       int (*yield)(struct gpiod_edge_event *event, void *user_data), void *user_data);

/*!
 * \brief Convert a line value to a string.
 * \param value The line value to convert.
 * \return A string representation of the line value ("active", "inactive", "error", or "unknown").
 */
const char *gpio_line_value_to_string(enum gpiod_line_value value);

/*!
 * \brief Convert an edge event type to a string.
 * \param event_type The edge event type to convert.
 * \return A string representation of the edge event type ("rising", "falling", or "unknown").
 */
const char *gpio_edge_event_type_to_string(enum gpiod_edge_event_type event_type);

void gpio_line_settings_free(void *line_settings);   /*!< Free a line settings object */
void gpio_line_config_free(void *line_config);       /*!< Free a line config object */
void gpio_request_config_free(void *request_config); /*!< Free a request config object */
void gpio_edge_event_buffer_free(void *buffer);      /*!< Free an edge event buffer object */

#endif /* GPIO_H */
